### ISSUE TITLE
Use eager debounce algorithm 

### ISSUE THREAD

**Issue by henrebotha** [ioridev/Precision-Fighting-Board#8]
The default debounce algorithm added in #7 adds latency to the button presses. Use [this alternative algorithm instead](https://github.com/thomasfredericks/Bounce2#lock-out-interval) (sometimes known as "eager debounce") to avoid this.

**Comment by ioridev** [comment]
Thanks for the good knowledge! This is an important fix.

**Comment by ioridev** [comment]
Do I just set it to BOUNCE_LOCK_OUT or what about BOUNCE_WITH_PROMPT_DETECTION?

**Comment by henrebotha** [comment]
I don't really know, I don't understand C very well. So I don't know if you've put the `define` in the right place or whatever.

**Comment by ioridev** [comment]
Understood. Thanks for the good insight anyway.

**Comment by ioridev** [comment]
I'm going to Close this issue for now, but I will look into it closely.

**Comment by ioridev** [comment]
#define BOUNCE_LOCK_OUT had to be written before #include <Bounce2.h>.
Fixed.
